---
title: "高成熟度概念概览MaHM Summary"
format: html
editor: visual
---

# 高成熟度概念培训资料

### **Data Descriptive / Visualization Techniques: 描述 / 图示化**

-   算术平均值 Mean

-   中位数 Median (Q2)

-   众数 Mode

-   四分位数 quartile Q1 Q2 Q3

-   Inter-quartile range (Q3 – Q1)

-   极差 Range

-   方差 Variance ( $\sigma^2$ )

-   标准差 Standard deviation ( $\sigma$ )

<!-- -->

-   箱线图 Box Whisker plot

-   运行图 Run chart

-   散点图 Scatter diagram

-   直方图 Histogram

-   帕累托图 Pareto chart

-   茎叶图 Stem and leaf plot

## Control Charts: 控制图

-   XmR , X-bar R , X-bar S

-   u / c charts, np / p charts

-   Special cause vs Common causes of variation 异常因素 ， 随机/通常 因素

-   Stability 稳定性

-   Capability 能力度

## Data types:Continuous 连续 vs Attribute分类/ 离散

-   Nominal 名义级

-   Ordinal 顺序级

-   Interval 间距级

-   Ratio 比率级

### Hypothesis testing:假设检验

-   Null Hypothesis ($H_0$) 零假定

-   Alternative Hypothesis ($H_A$) 非零假定

-   Type I error ( $\alpha$ ) 第一类错误

-   Type II error ( $\beta$ ) 第二类错误

-   P-value P值

-   Practical difference ( $\delta$ )

### **CMMI High Maturity concepts: 高成熟度**

-   Process Performance Baseline 过程性能基线

-   Segmentation and Stratification 分组

-   Process Performance Model 过程性能模型

-   Quality and Process Performance Objectives(QPPO) 质量和过程性能目标

-   Capability : Voice of the customer (VOC = USL / LSL) 客户声音 （规格上下限）； Voice of the process (VOP) 过程声音

过程能力指数：

$C_p = \cfrac{USL - LSL}{6 \sigma}$不考虑是否偏移，只考虑分布范围

$C_{pk} = Min [ \cfrac{USL - \mu}{3 \sigma} , \cfrac{\mu - LSL}{3 \sigma} ]$考虑偏移，选其中最少值

## Analysis tools and techniques: 分析技巧

-   2-sample t-Test 双样本 T检验

-   Regression 回归分析

-   ANOVA方差分析

-   Chi-square卡方

-   Logistic Regression 逻辑回归

-   Correlation 相关性 (Pearson , Spearman)

## 
